apiVersion: v1
appVersion: "8.9.4"
description: A simple demo Helm chart for HTCondor on Kubernetes 
name: htcondor
version: 0.0.1
maintainers:
  - name: dciangot
    email: diego.ciangottini@pg.infn.it
