apiVersion: apps/v1
kind: Deployment
metadata:
  name: wn-pod
  labels:
    app.kubernetes.io/name: wn
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wn
    spec:
      priorityClassName: system-node-critical
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - wn
            topologyKey: kubernetes.io/hostname
      #hostNetwork: true
      containers:
      - name: wn
        imagePullPolicy: IfNotPresent
        image: "htcondor/execute:8.9.9-el7"
        volumeMounts:
          - mountPath: "/etc/condor/config.d"
            name: configd
          - name: clustersecret
            mountPath: /etc/pwd
          - name: mapfile
            mountPath: /home/uwdir/
      volumes:
      - name: configd
        configMap:
          name: wnconfigd
      - name: clustersecret
        secret:
          secretName: clustersecret
          defaultMode: 256
      - name: mapfile
        configMap:
          name: mapfile
  selector:
    matchLabels:
      app.kubernetes.io/name: wn

  replicas: 1
---
# Source: htcondor/templates/htc-master-pod.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-pod
  labels:
    app.kubernetes.io/name: client
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
    spec:
      priorityClassName: system-node-critical
      #hostNetwork: true
      containers:
      - name: client
        imagePullPolicy: IfNotPresent
        image: "htcondor/execute:8.9.9-el7"
        command:
          - sleep
          - infinity
        volumeMounts:
          - name: clustersecret
            mountPath: /etc/pwd
      volumes:
      - name: clustersecret
        secret:
          secretName: clustersecret
          defaultMode: 256
      - name: mapfile
        configMap:
          name: mapfile
  selector:
    matchLabels:
      app.kubernetes.io/name: client

  replicas: 1
